### ISSUE TITLE
Launching via adb shell crashes Wolvic on Quest 2

### ISSUE THREAD

**Issue by Squareys** [Igalia/wolvic#692]
## Configuration

Wolvic version: From Quest Store, 03/16/2023
Wolvic build ID: ?

Hardware: Meta Quest 2

## Steps to Reproduce
1. Run `adb shell am start -a android.intent.action.VIEW -d "https://aframe.io" com.igalia.wolvic/com.igalia.wolvic.VRBrowserActivity` as [suggested by the docs](https://github.com/Igalia/wolvic#debugging-tips)

## Current Behavior
Wolvic crashes.

## Expected Behavior
Wolvic launches with URL

## Context
Originally run from Wonderland Engine to launch the project into Wolvic, but reproducible via Meta Quest Developer Hub.

## Error Logs and Stack Traces
```
04-30 23:54:03.717  1051  1144 I ActivityManager: Start proc 8286:com.igalia.wolvic/u0a89 for pre-top-activity {com.igalia.wolvic/com.igalia.wolvic.VRBrowserActivity}
04-30 23:54:03.718  1051  1354 W AppHibernationService: Attempted to call isHibernatingForUser on unsupported device.
04-30 23:54:03.734  1051  1354 W AppHibernationService: Attempted to call isHibernatingForUser on unsupported device.
04-30 23:54:03.757  1051  5461 I DisplayDeviceRepository: Display device removed: DisplayDeviceInfo{"com.oculus.android_panel_app.AndroidPanelLayer-controlbar4": uniqueId="virtual:com.oculus.systemux,10039,com.oculus.android_panel_app.AndroidPanelLayer-controlbar4,0", 1000 x 50, modeId 472, defaultModeId 472, supportedModes [{id=472, width=1000, height=50, fps=60.0, alternativeRefreshRates=[]}], colorMode 0, supportedColorModes [0], hdrCapabilities null, allmSupported false, gameContentTypeSupported false, density 200, 200.0 x 200.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, deviceProductInfo null, state ON, owner com.oculus.systemux (uid 10039), frameRateOverride , brightnessMinimum 0.0, brightnessMaximum 0.0, brightnessDefault 0.0, FLAG_PRIVATE, FLAG_NEVER_BLANK, FLAG_OWN_CONTENT_ONLY}
04-30 23:54:03.758  1051  5461 I LogicalDisplayMapper: Removing display: 412
04-30 23:54:01.921     0     0 I binder  : 8286:8286 ioctl 40046210 7fd123e364 returned -22
04-30 23:54:01.940     0     0 I [drm:dsi_display_set_mode] [msm-dsi-info]: mdp_transfer_time_us=0 us
04-30 23:54:01.940     0     0 I [drm:dsi_display_set_mode] [msm-dsi-info]: hactive= 1920,vactive= 3664,fps=72
04-30 23:54:03.850  1051  1134 W NotificationHistory: Attempted to remove channel for locked/gone/disabled user 0
04-30 23:54:03.900  8286  8306 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
04-30 23:54:03.900  8286  8306 E AndroidRuntime: Process: com.igalia.wolvic, PID: 8286
04-30 23:54:03.900  8286  8306 E AndroidRuntime: java.lang.IllegalArgumentException: com.igalia.wolvic: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
04-30 23:54:03.900  8286  8306 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:4)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:1)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:8)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:1)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-30 23:54:03.900  8286  8306 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
04-30 23:54:03.905  1051  8313 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
04-30 23:54:03.906  1051  1348 W ActivityTaskManager:   Force finishing activity com.igalia.wolvic/.VRBrowserActivity
04-30 23:54:03.933  1051  5461 I ActivityManager: Process com.igalia.wolvic (pid 8286) has died: fg  TOP 
```
<details open>

```
```

</details>

**Comment by svillar** [comment]
Hi Jonathan!,

thanks for reporting. This is an already known issue and was fixed some time ago as part of #602. Which version are you using? Because 1.3.4 should have a fix for that.

**Comment by Squareys** [comment]
@svillar I'm using the version released to the Quest Store on 03/16/2023 I can check the version number later.
Great to hear it's fixed!

**Comment by Squareys** [comment]
@svillar 1.3.4 does not seem to fix the issue, but it might be a different crash log now.

**Comment by svillar** [comment]
I've just tried and it works fine here. That error was caused by the recent upgrade of OS version in Meta devices. We detected it before the release was shipped and fixed it. That's why it's so weird that you are getting it. Are you sure you don't have multiple versions of Wolvic installed or something?

Mind opening the settings window and click on the version code until you see a hash like string and paste it here?
